//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kho2222.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoadon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hoadon()
        {
            this.CThoadons = new HashSet<CThoadon>();
        }
    
        public string maHD { get; set; }
        public Nullable<System.DateTime> ngayban { get; set; }
        public string tk { get; set; }
        public string maKH { get; set; }
        public Nullable<int> thanhtoan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CThoadon> CThoadons { get; set; }
        public virtual kh kh { get; set; }
    }
}
