//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kho2222.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kho2Entities : DbContext
    {
        public kho2Entities()
            : base("name=kho2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CThoadon> CThoadons { get; set; }
        public virtual DbSet<CTphieunhap> CTphieunhaps { get; set; }
        public virtual DbSet<hang> hangs { get; set; }
        public virtual DbSet<hoadon> hoadons { get; set; }
        public virtual DbSet<inventory> inventories { get; set; }
        public virtual DbSet<kh> khs { get; set; }
        public virtual DbSet<kho> khoes { get; set; }
        public virtual DbSet<loaiHG> loaiHGs { get; set; }
        public virtual DbSet<NCC> NCCs { get; set; }
        public virtual DbSet<NSX> NSXes { get; set; }
        public virtual DbSet<phieunhap> phieunhaps { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tk> tks { get; set; }
    }
}
