//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kho2222.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tk
    {
        public string tk1 { get; set; }
        public string mk { get; set; }
        public string mak { get; set; }
        public string chucvu { get; set; }
    
        public virtual kho kho { get; set; }
    }
}
