//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kho2222.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hang()
        {
            this.CThoadons = new HashSet<CThoadon>();
            this.CTphieunhaps = new HashSet<CTphieunhap>();
        }
    
        public string maHG { get; set; }
        public string tenHG { get; set; }
        public System.DateTime namSX { get; set; }
        public Nullable<System.DateTime> hanSD { get; set; }
        public string maLH { get; set; }
        public string maNSX { get; set; }
        public string tinhtrang { get; set; }
        public string mota { get; set; }
        public Nullable<double> thetich { get; set; }
        public Nullable<int> gia { get; set; }
        public string anh { get; set; }
        public Nullable<System.DateTime> ngaynhapkho { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CThoadon> CThoadons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTphieunhap> CTphieunhaps { get; set; }
        public virtual loaiHG loaiHG { get; set; }
        public virtual NSX NSX { get; set; }
    }
}
