//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kho2222.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phieunhap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public phieunhap()
        {
            this.CTphieunhaps = new HashSet<CTphieunhap>();
        }
    
        public string maPN { get; set; }
        public Nullable<System.DateTime> ngaynhap { get; set; }
        public string maNCC { get; set; }
        public Nullable<int> tiennhap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTphieunhap> CTphieunhaps { get; set; }
        public virtual NCC NCC { get; set; }
    }
}
